### ISSUE TITLE
Packet Ack not correct

### ISSUE THREAD

**Issue by GNaD13** [notional-labs/fee-abstraction#47]
**ISSUE**
Currently, packet ack reflect from contract not correct. It only respone value(which is the raw data spot price from osmosis) [here](https://github.com/notional-labs/feeabstraction-contract/blob/main/contracts/fee-abstraction/src/ibc.rs#L119-L131)
```
let res = match deps.querier.raw_query(&raw) {
        SystemResult::Err(system_err) => Err(StdError::generic_err(format!(
            "Querier contract error: {}",
            system_err
        ))),
        SystemResult::Ok(ContractResult::Err(contract_err)) => Err(StdError::generic_err(format!(
            "Querier contract error: {}",
            contract_err
        ))),
        SystemResult::Ok(ContractResult::Ok(value)) => Ok(IbcReceiveResponse::<Empty>::new()
            .set_ack(value)
            .add_attribute("action", "receive_ibc_query")),
   };
```
=> To read this data, we just need to have json unmarshal with types.SpotPrice (Current running in vuong/testingquery branch). 
https://github.com/notional-labs/fee-abstraction/blob/434d65d2a882986ecec5fe75fd3b17a1987a1c76/x/feeabs/ibc_module.go#L166-L174
We still can read this type of data but the thing is it may meet problem if the ibc reflect packet is error.
The value should be embedded in SDK ACK packet struct (channeltypes.Acknowledgement) so feeabs chain module can handle the ibc ack packet.

**SOLUTION**

- Contract: Embedded spot price value in ibc ack packet
```
let acknowledgement = to_binary(&AcknowledgementMsg::Ok(value))?;
    Ok(IbcReceiveResponse::new()
        .set_ack(acknowledgement)
        .add_attribute("key_attr", "attr_value"))
```
- Add check ack 

```
var ack channeltypes.Acknowledgement

if err := types.ModuleCdc.UnmarshalJSON(acknowledgement, &ack); err != nil {
	return sdkerrors.Wrapf(sdkerrors.ErrUnknownRequest, "cannot unmarshal packet acknowledgement: %v", err)
}

switch resp := ack.Response.(type) {
case *channeltypes.Acknowledgement_Result:
    // Ack success logic
case *channeltypes.Acknowledgement_Error:
    // Ack error logic
}
```

**Comment by GNaD13** [comment]
@expertdicer pls check this issue, can you fix with contract side pls? I will handle with the chain side.
@vuong177 some minor issue, but i think we can still use current version for demo. The result is unaffected

**Comment by expertdicer** [comment]
Done this with https://github.com/notional-labs/feeabstraction-contract/pull/6
