### ISSUE TITLE
Clean all TODO comments.

### ISSUE THREAD

**Issue by vuong177** [notional-labs/fee-abstraction#67]

**Comment by vuong177** [comment]
@GNaD13

**Comment by nicolaslara** [comment]
Noticed this is still open and there's at least one todo I noticed that is important to remove before v1.0:  https://github.com/notional-labs/fee-abstraction/blob/main/x/feeabs/keeper/ibc.go#L251-L254

**Comment by GNaD13** [comment]
Thank you sir @nicolaslara
